package com.example.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class WishlistItem(
    val id: Long = 0,
    @SerialName("common_name") val commonName: String,
    @SerialName("latin_name") val latinName: String?,
    @SerialName("description") val description: String?,
    @SerialName("match_percentage") val matchPercentage: Int?,
    @SerialName("tags") val tags: String?,
    @SerialName("scan_mode") val scanMode: String,
    @SerialName("created_at") val createdAt: String? = null
)

// Separate insert model — excludes id and created_at which are auto-generated by Supabase
@Serializable
data class WishlistInsert(
    @SerialName("common_name") val commonName: String,
    @SerialName("latin_name") val latinName: String?,
    @SerialName("description") val description: String?,
    @SerialName("match_percentage") val matchPercentage: Int?,
    @SerialName("tags") val tags: String?,
    @SerialName("scan_mode") val scanMode: String
)
